spring.application.name=pethealthapp

spring.datasource.url=jdbc:postgresql://localhost:5432/pethealthapp
spring.datasource.username=petuser
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
